language: c
addons:
    apt:
        #        sources:
        packages:
            - gcc-avr
            - binutils-avr
            - avr-libc
before_install:
    #  - sudo apt-get update -qq
    #  - sudo apt-get install -qq gcc-avr binutils-avr avr-libc
  - openssl aes-256-cbc -K $encrypted_384a0b2b175f_key -iv $encrypted_384a0b2b175f_iv
  -in deploy_key.enc -out settings/keys/deploy_key -d
#install:
#before_script:
script: 
  bash ./deploy.sh
#after_sucess:
#after_failure

branches:
  except:
  - gh-pages 
env:
  global:
  - GH_REPO_NAME: Acionamento2017
  - DOXYFILE: "$TRAVIS_BUILD_DIR/firmware/"
  - GH_REPO_REF: github.com/ZeniteSolar/Acionamento2017.git
  - ENCRYPTION_LABEL: "0a6446eb3ae3"
  - COMMIT_AUTHOR_EMAIL: joao.maker@gmail.com
