---
#sudo: false
language: c
before_install:
  - sudo apt-get update -qq
  - openssl aes-256-cbc -K $encrypted_384a0b2b175f_key -iv $encrypted_384a0b2b175f_iv
  -in deploy_key.enc -out settings/keys/deploy_key -d
install:
  - sudo apt-get install -qq git gcc-avr binutils-avr avr-libc
script: 
  bash ./deploy.sh
branches:
  except:
  - gh-pages 
env:
  global:
  - GH_REPO_NAME: Acionamento2017
  - DOXYFILE: "$TRAVIS_BUILD_DIR/firmware/"
  - GH_REPO_REF: github.com/ZeniteSolar/Acionamento2017.git
  - ENCRYPTION_LABEL: "0a6446eb3ae3"
  - COMMIT_AUTHOR_EMAIL: joao.maker@gmail.com
